# Generated by Django 5.2.17 on 2026-09-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_school_twilio_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_billed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collection_efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Collection rate as a percentage (0–100).', max_digits=6)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('automated_resolved_count', models.PositiveIntegerField(default=0)),
                ('escalated_count', models.PositiveIntegerField(default=0)),
                ('summary_markdown', models.TextField(blank=True)),
                ('key_action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['-year', '-week_number', '-created_at'],
                'indexes': [models.Index(fields=['school', '-year', '-week_number'], name='dashboard_e_school__ce6d80_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'year', 'week_number'), name='dashboard_unique_weekly_report_per_school')],
            },
        ),
    ]
