# Generated by Django 5.2.17 on 2026-09-10 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_fee_invoice_payment_transaction_models'),
        ('finance', '0002_feestructure_charge_fields'),
        ('tenants', '0003_invitation_status_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='e.g. Term 2 2026', max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='academics.student')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promised_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HONORED', 'Honored'), ('BROKEN', 'Broken')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='finance.feeinvoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['promised_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='E.164 format, e.g. +254712345678', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid E.164 phone number, e.g. +254712345678.', regex='^\\+[1-9]\\d{6,14}$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('STK_PUSH_SENT', 'STK push sent'), ('SUCCESS', 'Success'), ('FAILED_USER', 'Failed (user)'), ('FAILED_TIMEOUT', 'Failed (timeout)'), ('FAILED_ERROR', 'Failed (error)')], default='INITIALIZED', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('raw_callback_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.feeinvoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=16)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.feeinvoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='finance.paymenttransaction')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'verbose_name_plural': 'fee categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='finance_unique_fee_category_per_school')],
            },
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['school', 'status'], name='finance_fee_school__703b56_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinvoice',
            index=models.Index(fields=['school', 'due_date'], name='finance_fee_school__7274c9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['school', 'status'], name='finance_pay_school__81c5f4_idx'),
        ),
    ]
