# Generated by Django 5.2.17 on 2026-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_fee_invoice_payment_transaction_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, help_text='When the guardian was last messaged about this invoice.', null=True),
        ),
    ]
