# Generated by Django 5.2.17 on 2026-09-10 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_fee_invoice_payment_transaction_models'),
        ('finance', '0004_fee_reminder_last_contacted'),
        ('tenants', '0005_school_twilio_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('term', models.CharField(help_text='e.g. Term 1 2026', max_length=64)),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_term_fee_plans', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(blank=True, help_text='Leave empty to bill all active students in the school.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_fee_plans', to='academics.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermFeeLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_line_items', to='finance.feecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.termfeeplan')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='termfeeplan',
            index=models.Index(fields=['school', 'term'], name='finance_ter_school__9592ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='termfeelineitem',
            constraint=models.UniqueConstraint(fields=('plan', 'category'), name='finance_unique_line_item_per_plan_category'),
        ),
    ]
