# Generated by Django 5.2.17 on 2026-09-10 06:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_term_fee_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bursary, scholarship, or waiver credited against this invoice.', max_digits=12),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='discount_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
