# Generated by Django 5.2.17 on 2026-09-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fee_credit_and_invoice_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_whatsapp_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the digital receipt WhatsApp was first delivered.', null=True),
        ),
    ]
