# Generated by Django 5.2.17 on 2026-09-10 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_default_stream_per_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Default teacher copied onto the class Main stream.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
