# Generated by Django 5.2.17 on 2026-09-12 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_attendance_record'),
        ('tenants', '0008_receipt_ops_weekly_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyParentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the school week (Africa/Nairobi).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent')], default='DRAFT', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_parent_updates_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_parent_updates_sent', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_parent_updates', to='academics.classstream')),
            ],
            options={
                'ordering': ['-week_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_summary', models.CharField(blank=True, max_length=255)),
                ('teacher_note', models.TextField(blank=True)),
                ('polished_note', models.TextField(blank=True)),
                ('message_body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_reason', models.CharField(blank=True, max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_feedback', to='academics.student')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_lines', to='academics.weeklyparentupdate')),
            ],
            options={
                'ordering': ['student__admission_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyparentupdate',
            constraint=models.UniqueConstraint(fields=('school', 'stream', 'week_start'), name='academics_unique_weekly_update_per_stream_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklystudentfeedback',
            constraint=models.UniqueConstraint(fields=('update', 'student'), name='academics_unique_weekly_feedback_per_student'),
        ),
    ]
