# Generated by Django 5.2.17 on 2026-09-10 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_fee_invoice_payment_transaction_models'),
        ('tenants', '0004_school_mpesa_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='E.164 format, e.g. +254712345678', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid E.164 phone number, e.g. +254712345678.', regex='^\\+[1-9]\\d{6,14}$')])),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('students', models.ManyToManyField(blank=True, related_name='parent_contacts', to='academics.student')),
            ],
            options={
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOT_ACTIVE', 'Bot active'), ('ESCALATED_PENDING', 'Escalated pending'), ('STAFF_ACTIVE', 'Staff active'), ('CLOSED', 'Closed')], default='BOT_ACTIVE', max_length=32)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_student', models.ForeignKey(blank=True, help_text='Locks context when a parent has multiple children.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='academics.student')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='communications.parentcontact')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=16)),
                ('sender', models.CharField(choices=[('PARENT', 'Parent'), ('BOT', 'Bot'), ('STAFF', 'Staff')], max_length=16)),
                ('body', models.TextField()),
                ('twilio_message_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('delivery_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='communicati_school__5e61f7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='parentcontact',
            constraint=models.UniqueConstraint(fields=('school', 'phone_number'), name='communications_unique_parent_phone_per_school'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['school', 'status'], name='communicati_school__483656_idx'),
        ),
    ]
