# Generated by Django 5.2.17 on 2026-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial_parent_conversation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcontact',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, help_text='When this parent was last contacted by an outbound bot reminder.', null=True),
        ),
    ]
