# Generated by Django 5.2.17 on 2026-09-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_broadcast_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcontact',
            name='reminders_paused_at',
            field=models.DateTimeField(blank=True, help_text='When fee reminders were paused (STOP / staff). Null = reminders allowed.', null=True),
        ),
        migrations.AddField(
            model_name='parentcontact',
            name='reminders_paused_reason',
            field=models.CharField(blank=True, help_text='parent_stop | staff_pause', max_length=32),
        ),
    ]
