# Generated by Django 5.2.17 on 2026-09-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_invitation_status_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mpesa_consumer_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='mpesa_consumer_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='mpesa_passkey',
            field=models.TextField(blank=True),
        ),
    ]
