# Generated by Django 5.2.17 on 2026-09-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_school_mpesa_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='Optional WhatsApp sender override (E.164). Falls back to TWILIO_WHATSAPP_NUMBER.', max_length=16),
        ),
    ]
