# Generated by Django 5.2.17 on 2026-09-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_audit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmembership',
            name='is_bursar',
            field=models.BooleanField(default=False, help_text='Can manage fees, Paybill settings, invoices, and collections.'),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='role_bursar',
            field=models.BooleanField(default=False),
        ),
    ]
