# Generated by Django 5.2.17 on 2026-09-12 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_bursar_and_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmembership',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional staff WhatsApp for ops reminders (E.164 preferred).', max_length=16),
        ),
        migrations.CreateModel(
            name='OpsJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FAILED', 'Failed')], max_length=16)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, help_text='Null = platform-wide job (e.g. database backup).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_job_runs', to='tenants.school')),
            ],
            options={
                'ordering': ['-finished_at'],
                'indexes': [models.Index(fields=['job_name', '-finished_at'], name='tenants_ops_job_nam_9eba49_idx')],
            },
        ),
    ]
