# Generated by Django 5.2.17 on 2026-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_receipt_ops_weekly_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mpesa_environment',
            field=models.CharField(blank=True, choices=[('', 'Platform default'), ('sandbox', 'Sandbox'), ('production', 'Production')], help_text='Daraja API host. Blank uses DARAJA_ENVIRONMENT from the server. Use production only with live Safaricom credentials.', max_length=16),
        ),
    ]
