# Generated by Django 5.2.17 on 2026-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_mpesa_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='daraja_webhook_secret',
            field=models.TextField(blank=True),
        ),
    ]
