# Generated by Django 5.2.17 on 2026-09-12 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_school_daraja_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBillingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('starter_max_students', models.PositiveIntegerField(default=300)),
                ('growth_max_students', models.PositiveIntegerField(default=750)),
                ('starter_rate', models.DecimalField(decimal_places=2, default=120, max_digits=10)),
                ('growth_rate', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('scale_rate', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('starter_floor', models.DecimalField(decimal_places=2, default=20000, max_digits=12)),
                ('trial_days', models.PositiveIntegerField(default=30)),
                ('post_trial_grace_days', models.PositiveIntegerField(default=14)),
                ('term_half_due_days', models.PositiveIntegerField(default=14)),
                ('term_full_due_days', models.PositiveIntegerField(default=30)),
                ('min_proration_factor', models.DecimalField(decimal_places=4, default=0.5, help_text='Minimum first-invoice proration factor (e.g. 0.5 = 50%).', max_digits=5)),
                ('roll_into_next_term_days', models.PositiveIntegerField(default=14, help_text='If fewer than this many days remain in the current term when the trial ends, roll the first charge into the next term.')),
                ('soft_lock_message', models.TextField(blank=True, default='This school is locked until the Kora subscription payment is caught up. You can still switch to other schools.')),
                ('pay_instructions', models.TextField(blank=True, default='Pay the amount due to Kora using the instructions provided by your account manager. Your invoice will be marked paid once payment is confirmed (usually within 1 business day).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform billing settings',
                'verbose_name_plural': 'platform billing settings',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='applicant_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='county',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='estimated_student_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending_review', max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SchoolApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('school_registration', 'School registration / MoE licence'), ('applicant_id', 'Applicant National ID / passport'), ('authority_letter', 'Authority letter'), ('kra_pin', 'KRA PIN (optional)'), ('cr12', 'CR12 (optional)'), ('other', 'Other')], max_length=32)),
                ('file', models.FileField(upload_to='school_applications/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='tenants.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_school_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_state', models.CharField(choices=[('trial', 'Trial'), ('ok', 'In good standing'), ('grace', 'Grace period'), ('locked', 'Soft-locked')], db_index=True, default='trial', max_length=16)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_term_label', models.CharField(blank=True, max_length=64)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.school')),
            ],
            options={
                'ordering': ['school__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolTermPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year_label', models.CharField(max_length=32)),
                ('term_number', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_periods', to='tenants.school')),
            ],
            options={
                'ordering': ['academic_year_label', 'term_number'],
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_label', models.CharField(max_length=64)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale')], max_length=16)),
                ('rate_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proration_factor', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_half_at', models.DateField(blank=True, null=True)),
                ('due_full_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='open', max_length=16)),
                ('is_first_billable', models.BooleanField(default=False, help_text='First invoice after trial (may be mid-term prorated).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='tenants.school')),
                ('term_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_invoices', to='tenants.schooltermperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='schooltermperiod',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year_label', 'term_number'), name='tenants_unique_school_term_period'),
        ),
        migrations.AddConstraint(
            model_name='schooltermperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='tenants_term_period_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['school', 'status'], name='tenants_pla_school__fa6098_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['school', 'term_label'], name='tenants_pla_school__1f4b9e_idx'),
        ),
    ]
