# Generated by Django 5.2.17 on 2026-09-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_backfill_school_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbillingsettings',
            name='census_policy_text',
            field=models.TextField(blank=True, default='Your main term fee is set from active students on day 14 of the term (census lock). Students who join or leave after that are settled once at term end as a net adjustment at half the per-student term rate. Growth creates a small add-on invoice. Net losses become credit on your next term bill — we do not issue cash refunds. Changes under 10 students are ignored as normal churn.'),
        ),
        migrations.AddField(
            model_name='platformbillingsettings',
            name='true_up_factor',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Fraction of full per-student term rate for end-of-term net adjustments.', max_digits=5),
        ),
        migrations.AddField(
            model_name='platformbillingsettings',
            name='true_up_min_delta',
            field=models.PositiveIntegerField(default=10, help_text='Ignore net student changes smaller than this at term end.'),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='census_lock_date',
            field=models.DateField(blank=True, help_text='Date the day-14 census locks (usually term start + 14).', null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='census_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='census_status',
            field=models.CharField(choices=[('provisional', 'Provisional (pre day-14)'), ('locked', 'Census locked')], default='provisional', max_length=16),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subscription credit applied when this invoice was issued.', max_digits=12),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='headcount_delta',
            field=models.IntegerField(default=0, help_text='For true-ups: net students vs locked census (can be negative).'),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='kind',
            field=models.CharField(choices=[('main', 'Main term invoice'), ('true_up', 'End-of-term true-up'), ('credit_note', 'Credit note')], db_index=True, default='main', max_length=16),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='related_invoice',
            field=models.ForeignKey(blank=True, help_text='Parent main invoice for true-ups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='tenants.platforminvoice'),
        ),
        migrations.AddField(
            model_name='platforminvoice',
            name='true_up_settled_at',
            field=models.DateTimeField(blank=True, help_text='When end-of-term net adjustment was processed for this main invoice.', null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KES credit from net mid-term student losses; applied to the next main invoice.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(fields=['school', 'kind', 'status'], name='tenants_pla_school__f928ac_idx'),
        ),
    ]
