# Generated by Django 5.2.17 on 2026-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_backfill_invoice_census'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmembership',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When the admin dismissed the Get started checklist for this school.', null=True),
        ),
    ]
