from django.urls import path
from django.views.generic import RedirectView

from communications.views import (
    BroadcastCreateView,
    BroadcastListView,
    BroadcastPreviewView,
)
from dashboard.views import (
    AssignClassTeacherView,
    AssignGradeTeacherView,
    AuditLogView,
    ChatClaimView,
    ChatConsoleView,
    ChatMessagesPartialView,
    ChatReleaseView,
    ChatResolveView,
    ChatSendView,
    ClassStreamAssignmentView,
    ConversationConsoleView,
    DashboardOverviewView,
    ExecutiveReportDetailView,
    ExecutiveReportListView,
    GradeCreateView,
    GradeEditView,
    GradeFinanceView,
    GradeHomeView,
    GradeStudentCreateView,
    GradeStudentEditView,
    GradeStudentImportTemplateView,
    GradeStudentImportView,
    OnboardingChecklistView,
    PaymentsExportView,
    SchoolSettingsView,
    StreamAttendanceView,
    StreamCreateView,
    StreamDeleteView,
    StreamEditView,
    StreamFinanceView,
    StreamRosterView,
    StudentCreateView,
    StudentEditView,
    StudentImportTemplateView,
    StudentImportView,
    StudentsExportView,
    TeacherManagementView,
    WeeklyParentUpdateView,
)

app_name = 'dashboard'

urlpatterns = [
    # Canonical paths
    path('overview/', DashboardOverviewView.as_view(), name='overview'),
    path('settings/', SchoolSettingsView.as_view(), name='school_settings'),
    path('onboarding/', OnboardingChecklistView.as_view(), name='onboarding'),
    path('audit/', AuditLogView.as_view(), name='audit_log'),
    path('staff/', TeacherManagementView.as_view(), name='teachers'),
    path('classes/', ClassStreamAssignmentView.as_view(), name='classes'),
    path('classes/new/', GradeCreateView.as_view(), name='grade_create'),
    path(
        'classes/<slug:grade_slug>/edit/',
        GradeEditView.as_view(),
        name='grade_edit',
    ),
    path(
        'classes/<slug:grade_slug>/assign-teacher/',
        AssignGradeTeacherView.as_view(),
        name='assign_grade_teacher',
    ),
    path(
        'classes/<slug:grade_slug>/streams/new/',
        StreamCreateView.as_view(),
        name='stream_create',
    ),
    path(
        'classes/streams/<slug:stream_slug>/edit/',
        StreamEditView.as_view(),
        name='stream_edit',
    ),
    path(
        'classes/streams/<slug:stream_slug>/delete/',
        StreamDeleteView.as_view(),
        name='stream_delete',
    ),
    path(
        'classes/streams/<slug:stream_slug>/assign-teacher/',
        AssignClassTeacherView.as_view(),
        name='assign_teacher',
    ),
    path(
        'grades/<slug:grade_slug>/',
        GradeHomeView.as_view(),
        name='grade_home',
    ),
    path(
        'grades/<slug:grade_slug>/finance/',
        GradeFinanceView.as_view(),
        name='grade_finance',
    ),
    path(
        'grades/<slug:grade_slug>/students/new/',
        GradeStudentCreateView.as_view(),
        name='grade_student_create',
    ),
    path(
        'grades/<slug:grade_slug>/students/<str:admission_number>/edit/',
        GradeStudentEditView.as_view(),
        name='grade_student_edit',
    ),
    path(
        'grades/<slug:grade_slug>/import/',
        GradeStudentImportView.as_view(),
        name='grade_student_import',
    ),
    path(
        'grades/<slug:grade_slug>/import/template/',
        GradeStudentImportTemplateView.as_view(),
        name='grade_student_import_template',
    ),
    path(
        'streams/<slug:stream_slug>/roster/',
        StreamRosterView.as_view(),
        name='stream_roster',
    ),
    path(
        'streams/<slug:stream_slug>/attendance/',
        StreamAttendanceView.as_view(),
        name='stream_attendance',
    ),
    path(
        'streams/<slug:stream_slug>/weekly-update/',
        WeeklyParentUpdateView.as_view(),
        name='weekly_parent_update',
    ),
    path(
        'streams/<slug:stream_slug>/finance/',
        StreamFinanceView.as_view(),
        name='stream_finance',
    ),
    path(
        'streams/<slug:stream_slug>/students/new/',
        StudentCreateView.as_view(),
        name='student_create',
    ),
    path(
        'streams/<slug:stream_slug>/students/<str:admission_number>/edit/',
        StudentEditView.as_view(),
        name='student_edit',
    ),
    path(
        'streams/<slug:stream_slug>/import/',
        StudentImportView.as_view(),
        name='student_import',
    ),
    path(
        'streams/<slug:stream_slug>/import/template/',
        StudentImportTemplateView.as_view(),
        name='student_import_template',
    ),
    path('broadcasts/', BroadcastListView.as_view(), name='broadcast_list'),
    path(
        'broadcasts/create/',
        BroadcastCreateView.as_view(),
        name='broadcast_create',
    ),
    path(
        'broadcasts/preview/',
        BroadcastPreviewView.as_view(),
        name='broadcast_preview',
    ),
    path('reports/', ExecutiveReportListView.as_view(), name='report_list'),
    path(
        'reports/<int:report_id>/',
        ExecutiveReportDetailView.as_view(),
        name='report_detail',
    ),
    path('whatsapp/', ChatConsoleView.as_view(), name='chat_console'),
    path(
        'whatsapp/<int:session_id>/',
        ChatConsoleView.as_view(),
        name='chat_console_session',
    ),
    path(
        'whatsapp/<int:session_id>/messages/',
        ChatMessagesPartialView.as_view(),
        name='chat_messages',
    ),
    path(
        'whatsapp/<int:session_id>/send/',
        ChatSendView.as_view(),
        name='chat_send',
    ),
    path(
        'whatsapp/<int:session_id>/claim/',
        ChatClaimView.as_view(),
        name='chat_claim',
    ),
    path(
        'whatsapp/<int:session_id>/release/',
        ChatReleaseView.as_view(),
        name='chat_release',
    ),
    path(
        'whatsapp/<int:session_id>/resolve/',
        ChatResolveView.as_view(),
        name='chat_resolve',
    ),
    path(
        'conversations/<int:session_id>/',
        ConversationConsoleView.as_view(),
        name='conversation_console',
    ),
    path(
        'exports/students/',
        StudentsExportView.as_view(),
        name='students_export',
    ),
    path(
        'exports/payments/',
        PaymentsExportView.as_view(),
        name='payments_export',
    ),
    # Legacy path redirects (bookmarks / old links)
    path(
        'app/',
        RedirectView.as_view(
            pattern_name='dashboard:overview',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'teachers/',
        RedirectView.as_view(
            pattern_name='dashboard:teachers',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/settings/',
        RedirectView.as_view(
            pattern_name='dashboard:school_settings',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/onboarding/',
        RedirectView.as_view(
            pattern_name='dashboard:onboarding',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/audit/',
        RedirectView.as_view(
            pattern_name='dashboard:audit_log',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/fees/',
        RedirectView.as_view(
            pattern_name='finance:fee_ledger',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/fees/<path:rest>',
        RedirectView.as_view(
            url='/finance/%(rest)s',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/broadcasts/',
        RedirectView.as_view(
            pattern_name='dashboard:broadcast_list',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/broadcasts/<path:rest>',
        RedirectView.as_view(
            url='/broadcasts/%(rest)s',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/reports/',
        RedirectView.as_view(
            pattern_name='dashboard:report_list',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/reports/<path:rest>',
        RedirectView.as_view(
            url='/reports/%(rest)s',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/chats/',
        RedirectView.as_view(
            pattern_name='dashboard:chat_console',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/chats/<path:rest>',
        RedirectView.as_view(
            url='/whatsapp/%(rest)s',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/conversations/<int:session_id>/',
        RedirectView.as_view(
            pattern_name='dashboard:conversation_console',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/exports/students/',
        RedirectView.as_view(
            pattern_name='dashboard:students_export',
            permanent=False,
            query_string=True,
        ),
    ),
    path(
        'dashboard/exports/payments/',
        RedirectView.as_view(
            pattern_name='dashboard:payments_export',
            permanent=False,
            query_string=True,
        ),
    ),
]
