from django.urls import path

from communications.views import (
    BroadcastCreateView,
    BroadcastListView,
    BroadcastPreviewView,
)
from dashboard.views import (
    AssignClassTeacherView,
    AssignGradeTeacherView,
    ChatClaimView,
    ChatConsoleView,
    ChatMessagesPartialView,
    ChatReleaseView,
    ChatResolveView,
    ChatSendView,
    ClassStreamAssignmentView,
    ConversationConsoleView,
    DashboardOverviewView,
    ExecutiveReportDetailView,
    ExecutiveReportListView,
    FeeLedgerSearchView,
    FeeLedgerStkPushView,
    FeeLedgerView,
    GradeCreateView,
    GradeEditView,
    GradeFinanceView,
    GradeHomeView,
    GradeStudentCreateView,
    GradeStudentEditView,
    GradeStudentImportTemplateView,
    GradeStudentImportView,
    StreamCreateView,
    StreamFinanceView,
    StreamRosterView,
    StudentCreateView,
    StudentEditView,
    StudentImportTemplateView,
    StudentImportView,
    TeacherManagementView,
)

app_name = 'dashboard'

urlpatterns = [
    path('app/', DashboardOverviewView.as_view(), name='overview'),
    path('dashboard/fees/', FeeLedgerView.as_view(), name='fee_ledger'),
    path(
        'dashboard/fees/search/',
        FeeLedgerSearchView.as_view(),
        name='fee_ledger_search',
    ),
    path(
        'dashboard/fees/stk/',
        FeeLedgerStkPushView.as_view(),
        name='fee_ledger_stk',
    ),
    path(
        'dashboard/broadcasts/',
        BroadcastListView.as_view(),
        name='broadcast_list',
    ),
    path(
        'dashboard/broadcasts/create/',
        BroadcastCreateView.as_view(),
        name='broadcast_create',
    ),
    path(
        'dashboard/broadcasts/preview/',
        BroadcastPreviewView.as_view(),
        name='broadcast_preview',
    ),
    path(
        'dashboard/reports/',
        ExecutiveReportListView.as_view(),
        name='report_list',
    ),
    path(
        'dashboard/reports/<int:report_id>/',
        ExecutiveReportDetailView.as_view(),
        name='report_detail',
    ),
    path('dashboard/chats/', ChatConsoleView.as_view(), name='chat_console'),
    path(
        'dashboard/chats/<int:session_id>/',
        ChatConsoleView.as_view(),
        name='chat_console_session',
    ),
    path(
        'dashboard/chats/<int:session_id>/messages/',
        ChatMessagesPartialView.as_view(),
        name='chat_messages',
    ),
    path(
        'dashboard/chats/<int:session_id>/send/',
        ChatSendView.as_view(),
        name='chat_send',
    ),
    path(
        'dashboard/chats/<int:session_id>/claim/',
        ChatClaimView.as_view(),
        name='chat_claim',
    ),
    path(
        'dashboard/chats/<int:session_id>/release/',
        ChatReleaseView.as_view(),
        name='chat_release',
    ),
    path(
        'dashboard/chats/<int:session_id>/resolve/',
        ChatResolveView.as_view(),
        name='chat_resolve',
    ),
    path(
        'dashboard/conversations/<int:session_id>/',
        ConversationConsoleView.as_view(),
        name='conversation_console',
    ),
    path('teachers/', TeacherManagementView.as_view(), name='teachers'),
    path('classes/', ClassStreamAssignmentView.as_view(), name='classes'),
    path('classes/new/', GradeCreateView.as_view(), name='grade_create'),
    path(
        'classes/<slug:grade_slug>/edit/',
        GradeEditView.as_view(),
        name='grade_edit',
    ),
    path(
        'classes/<slug:grade_slug>/assign-teacher/',
        AssignGradeTeacherView.as_view(),
        name='assign_grade_teacher',
    ),
    path(
        'classes/<slug:grade_slug>/streams/new/',
        StreamCreateView.as_view(),
        name='stream_create',
    ),
    path(
        'classes/streams/<slug:stream_slug>/assign-teacher/',
        AssignClassTeacherView.as_view(),
        name='assign_teacher',
    ),
    path(
        'grades/<slug:grade_slug>/',
        GradeHomeView.as_view(),
        name='grade_home',
    ),
    path(
        'grades/<slug:grade_slug>/finance/',
        GradeFinanceView.as_view(),
        name='grade_finance',
    ),
    path(
        'grades/<slug:grade_slug>/students/new/',
        GradeStudentCreateView.as_view(),
        name='grade_student_create',
    ),
    path(
        'grades/<slug:grade_slug>/students/<str:admission_number>/edit/',
        GradeStudentEditView.as_view(),
        name='grade_student_edit',
    ),
    path(
        'grades/<slug:grade_slug>/import/',
        GradeStudentImportView.as_view(),
        name='grade_student_import',
    ),
    path(
        'grades/<slug:grade_slug>/import/template/',
        GradeStudentImportTemplateView.as_view(),
        name='grade_student_import_template',
    ),
    path(
        'streams/<slug:stream_slug>/roster/',
        StreamRosterView.as_view(),
        name='stream_roster',
    ),
    path(
        'streams/<slug:stream_slug>/finance/',
        StreamFinanceView.as_view(),
        name='stream_finance',
    ),
    path(
        'streams/<slug:stream_slug>/students/new/',
        StudentCreateView.as_view(),
        name='student_create',
    ),
    path(
        'streams/<slug:stream_slug>/students/<str:admission_number>/edit/',
        StudentEditView.as_view(),
        name='student_edit',
    ),
    path(
        'streams/<slug:stream_slug>/import/',
        StudentImportView.as_view(),
        name='student_import',
    ),
    path(
        'streams/<slug:stream_slug>/import/template/',
        StudentImportTemplateView.as_view(),
        name='student_import_template',
    ),
]
